FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY package*.json ./

RUN npm ci

COPY . .

ARG DATABASE_URL
ARG NEXT_PUBLIC_APP_URL
ARG SESSION_SECRET
ARG DROPBOX_APP_KEY
ARG DROPBOX_APP_SECRET
ARG DROPBOX_REFRESH_TOKEN
ARG DROPBOX_UPLOAD_SUB_FOLDER_PATH
ARG DROPBOX_CLEAR_CARE_NAMESPACE_ID
ARG SLACK_WEBHOOK_URL
ARG RESEND_FROM_EMAIL
ARG RESEND_API_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV SESSION_SECRET=$SESSION_SECRET
ENV DROPBOX_APP_KEY=$DROPBOX_APP_KEY
ENV DROPBOX_APP_SECRET=$DROPBOX_APP_SECRET
ENV DROPBOX_REFRESH_TOKEN=$DROPBOX_REFRESH_TOKEN
ENV DROPBOX_UPLOAD_SUB_FOLDER_PATH=$DROPBOX_UPLOAD_SUB_FOLDER_PATH
ENV DROPBOX_CLEAR_CARE_NAMESPACE_ID=$DROPBOX_CLEAR_CARE_NAMESPACE_ID
ENV SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
ENV RESEND_API_KEY=$RESEND_API_KEY

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production

CMD ["npm", "start"]